DEBUG - 2025-10-24 13:39:25 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 13:44:02 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 13:44:18 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 13:44:18 --> mysqli_sql_exception: Table 'lms_lumabao.users' doesn't exist in engine in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2...', 'users.email', Array)
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2...', 'users.email', Array, NULL, 'email')
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2...', Array, Array, 'email')
#8 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run(Array)
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-10-24 13:44:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'lms_lumabao.users' doesn't exist in engine
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2@gmail.com', [...], [...], 'email')
 6 APPPATH\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 13:44:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'lms_lumabao.users' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...], null, 'email')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2@gmail.com', [...], [...], 'email')
 8 APPPATH\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 13:44:18 --> [Caused by] mysqli_sql_exception: Table 'lms_lumabao.users' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...], null, 'email')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2@gmail.com', [...], [...], 'email')
 9 APPPATH\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-24 13:52:14 --> mysqli_sql_exception: Table 'lms_lumabao.migrations' doesn't exist in engine in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MigrationRunner.php(660): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MigrationRunner.php(175): CodeIgniter\Database\MigrationRunner->getHistory('')
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\ITE311-LUMABAO\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
DEBUG - 2025-10-24 13:53:23 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 13:53:29 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 13:53:29 --> mysqli_sql_exception: Table 'lms_lumabao.users' doesn't exist in engine in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2...', 'users.email', Array)
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2...', 'users.email', Array, NULL, 'email')
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2...', Array, Array, 'email')
#8 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run(Array)
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-10-24 13:53:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'lms_lumabao.users' doesn't exist in engine
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 2 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...])
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2@gmail.com', [...], [...], 'email')
 6 APPPATH\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 13:53:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'lms_lumabao.users' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 4 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...])
 6 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...], null, 'email')
 7 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2@gmail.com', [...], [...], 'email')
 8 APPPATH\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 13:53:29 --> [Caused by] mysqli_sql_exception: Table 'lms_lumabao.users' doesn't exist in engine
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1
FROM `users`
WHERE `email` = \'almuhyilumabao2@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 5 SYSTEMPATH\Validation\Rules.php(175): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\Validation\StrictRules\Rules.php(187): CodeIgniter\Validation\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...])
 7 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('almuhyilumabao2@gmail.com', 'users.email', [...], null, 'email')
 8 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'Email', 'almuhyilumabao2@gmail.com', [...], [...], 'email')
 9 APPPATH\Controllers\Auth.php(70): CodeIgniter\Validation\Validation->run([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-10-24 13:56:18 --> mysqli_sql_exception: Tablespace for table '`lms_lumabao`.`migrations`' exists. Please DISCARD the tablespace before IMPORT in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `m...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `m...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `m...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `m...')
#4 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MigrationRunner.php(815): CodeIgniter\Database\Forge->createTable('migrations', true)
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MigrationRunner.php(162): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 C:\xampp\htdocs\ITE311-LUMABAO\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
DEBUG - 2025-10-24 14:21:36 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:21:37 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:21:49 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:22:08 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:22:08 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:22:16 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 14:22:16 --> mysqli_sql_exception: Table 'lms_lumabao.login_attempts' doesn't exist in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(257): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(230): App\Controllers\Auth->logLogin(NULL, false, 'Invalid email', 'almuhyilumabao2...')
#6 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(190): App\Controllers\Auth->handleFailedLogin(NULL, 'almuhyilumabao2...')
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-24 14:22:16 --> Failed to log login attempt: Table 'lms_lumabao.login_attempts' doesn't exist
DEBUG - 2025-10-24 14:22:16 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:22:36 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 14:22:36 --> mysqli_sql_exception: Table 'lms_lumabao.login_attempts' doesn't exist in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(257): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(230): App\Controllers\Auth->logLogin(NULL, false, 'Invalid email', '3lleyyy@gmail.c...')
#6 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(190): App\Controllers\Auth->handleFailedLogin(NULL, '3lleyyy@gmail.c...')
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-24 14:22:36 --> Failed to log login attempt: Table 'lms_lumabao.login_attempts' doesn't exist
DEBUG - 2025-10-24 14:22:36 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:22:49 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 14:22:49 --> mysqli_sql_exception: Table 'lms_lumabao.login_attempts' doesn't exist in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(257): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(230): App\Controllers\Auth->logLogin(NULL, false, 'Invalid email', '3lleyyy@gmail.c...')
#6 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(190): App\Controllers\Auth->handleFailedLogin(NULL, '3lleyyy@gmail.c...')
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-24 14:22:49 --> Failed to log login attempt: Table 'lms_lumabao.login_attempts' doesn't exist
DEBUG - 2025-10-24 14:22:49 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:22:54 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:22:56 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:23:01 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 14:23:01 --> mysqli_sql_exception: Table 'lms_lumabao.login_attempts' doesn't exist in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(257): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(230): App\Controllers\Auth->logLogin(NULL, false, 'Invalid email', '3lleyyy@gmail.c...')
#6 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(190): App\Controllers\Auth->handleFailedLogin(NULL, '3lleyyy@gmail.c...')
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-24 14:23:01 --> Failed to log login attempt: Table 'lms_lumabao.login_attempts' doesn't exist
DEBUG - 2025-10-24 14:23:01 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:23:03 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:23:12 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:23:34 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:23:47 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:23:47 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:23:53 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 14:23:53 --> mysqli_sql_exception: Table 'lms_lumabao.login_attempts' doesn't exist in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `lo...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(257): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(230): App\Controllers\Auth->logLogin(NULL, false, 'Invalid email', 'ako@gmail.com')
#6 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(190): App\Controllers\Auth->handleFailedLogin(NULL, 'ako@gmail.com')
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->login()
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-24 14:23:53 --> Failed to log login attempt: Table 'lms_lumabao.login_attempts' doesn't exist
DEBUG - 2025-10-24 14:23:53 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:30:59 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:31:01 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 14:47:42 --> mysqli_sql_exception: Duplicate entry '3lleyyy@gmail.com' for key 'email' in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1841): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', NULL, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(2230): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\ITE311-LUMABAO\app\Database\Seeds\UserSeeder.php(38): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\Seeder.php(149): App\Database\Seeds\UserSeeder->run()
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\ITE311-LUMABAO\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
DEBUG - 2025-10-24 14:48:37 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:48:37 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:49:01 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:49:01 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:49:18 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:49:18 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:49:37 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:51:01 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:51:03 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:51:13 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 14:51:14 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:16:48 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:17:55 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 15:17:55 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-24 15:17:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
[Method: GET, Route: dashboard]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 2 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:17:55 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 4 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:17:55 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 5 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-24 15:18:00 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:01 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 15:18:01 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-24 15:18:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
[Method: GET, Route: dashboard]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 2 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:18:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 4 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:18:01 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 5 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-24 15:18:05 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:05 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:22 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:22 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:38 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:38 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:41 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:43 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:43 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:49 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:49 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:51 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:18:53 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:19:04 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:19:06 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:19:27 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:19:29 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:21:30 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:21:31 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:21:32 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:21:32 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:22:53 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 15:22:53 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-24 15:22:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
[Method: GET, Route: dashboard]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 2 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:22:53 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 4 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:22:53 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 5 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-24 15:22:54 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:22:56 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:22:58 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 15:22:58 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-24 15:22:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
[Method: GET, Route: dashboard]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 2 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:22:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 4 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:22:58 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 5 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-24 15:23:04 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 15:23:04 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-24 15:23:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
[Method: GET, Route: dashboard]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 2 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:23:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 4 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:23:04 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 5 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-24 15:23:15 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:23:17 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:23:18 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:23:21 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:23:22 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
ERROR - 2025-10-24 15:23:22 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ITE311-LUMABAO\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ITE311-LUMABAO\app\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
#6 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\ITE311-LUMABAO\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ITE311-LUMABAO\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\ITE311-LUMABAO\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-24 15:23:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
[Method: GET, Route: dashboard]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 2 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:23:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 4 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-24 15:23:22 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = \'7\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `enrollments`
WHERE `user_id` = :user_id:', [...], false)
 5 APPPATH\Controllers\Auth.php(367): CodeIgniter\Database\BaseBuilder->countAllResults()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->dashboard()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-24 15:24:14 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:25:48 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:25:50 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:25:54 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:26:26 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:26:26 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:26:30 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:26:30 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:26:50 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:27:24 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:27:25 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:27:32 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:27:34 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:27:38 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:27:39 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:28:52 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
DEBUG - 2025-10-24 15:28:53 --> Session: Class initialized using 'App\Libraries\CustomSessionHandler' driver.
